### ISSUE TITLE
WikiMedia/Google Maps API

### ISSUE THREAD

**Issue by AyushManiSharma** [SMarquis85/P1-ShoppingMallsGenerator#7]
As a User
I want to see where the mall is
So That I can visit the mall

Acceptance Criteria:
When I click on a mall's information
Then I can see a static map,

Bonus: Ability to click on the map and get directions using Google Maps

**Comment by AyushManiSharma** [comment]
WikiMedia does not allow the use of Map tiles for third party users

**Comment by SMarquis85** [comment]
Google Maps API is functioning properly. (Still having issues with Wikipedia API.)
